# Generated by Django 5.1.7 on 2025-03-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
