# Generated by Django 5.1.7 on 2025-03-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file_path',
            new_name='mp3_path',
        ),
        migrations.AddField(
            model_name='song',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
