# Generated by Django 5.1.7 on 2025-04-02 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistCollab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'song')},
            },
        ),
    ]
