# Generated by Django 5.1.7 on 2025-03-31 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_premiumplan_remove_user_premium_end_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_subscription', to='payments.transaction'),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='premiumsubscription',
            unique_together={('user', 'transaction')},
        ),
    ]
