# Generated by Django 5.1.7 on 2025-04-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
