# Generated by Django 5.1.7 on 2025-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_video_videoplayhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='image_path',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
