# Generated by Django 5.1.7 on 2025-03-31 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_premiumsubscription_transaction_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumsubscription',
            name='transaction',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.transaction', unique=True),
        ),
    ]
