# Generated by Django 5.1.7 on 2025-04-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_premiumsubscription_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
