# Generated by Django 5.1.7 on 2025-04-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_artistregistrationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistregistrationrequest',
            old_name='stage_name',
            new_name='artist_name',
        ),
        migrations.AddField(
            model_name='artistregistrationrequest',
            name='artist_image',
            field=models.ImageField(blank=True, upload_to='artist_images/'),
        ),
        migrations.AddField(
            model_name='artistregistrationrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistregistrationrequest',
            name='identity_proof',
            field=models.ImageField(blank=True, upload_to='artist_identity/'),
        ),
        migrations.AddField(
            model_name='artistregistrationrequest',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
    ]
