# Generated by Django 5.1.7 on 2025-04-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_playlist_play_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
