# Generated by Django 5.1.7 on 2025-04-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_rename_stage_name_artistregistrationrequest_artist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistregistrationrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='artistregistrationrequest',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
    ]
