# Generated by Django 5.1.7 on 2025-04-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_remove_artistregistrationrequest_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistRegistrationRequest',
            new_name='ArtistRegistration',
        ),
    ]
