# Generated by Django 5.1.7 on 2025-04-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_rename_artistregistrationrequest_artistregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistregistration',
            name='artist_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artistregistration',
            name='identity_proof',
            field=models.TextField(blank=True),
        ),
    ]
