# -*- coding: utf-8 -*-

import datetime
from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from models.models import Role  # Điều chỉnh import theo cấu trúc dự án
from django.utils import timezone

User = get_user_model()

class Command(BaseCommand):
    help = 'Seed the database with initial user data'

    def handle(self, *args, **kwargs):
        # Tạo hoặc lấy các vai trò
        artist_role, _ = Role.objects.get_or_create(name='artist')

        # Danh sách người dùng để seed
        users_data = [
            {
                'email': 'traitimtrongvang@gmail.com',
                'username': 'traitimtrongvang@gmail.com',
                'password': 'Traitimtrongvang12345@',
                'name': 'traitimtrongvang"',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 11, 46, 16, 662495)),
            },
            {
                'email': 'nsutxuanhinh@gmail.com',
                'username': 'nsutxuanhinh@gmail.com',
                'password': 'Nsutxuanhinh12345@',
                'name': 'NSUT Xuân Hinh',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 1, 25)),
            },
            {
                'email': 'tuancry@gmail.com',
                'username': 'tuancry@gmail.com',
                'password': 'Tuancry12345@',
                'name': 'Tuấn Cry',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 11, 54, 20, 315551)),
            },
            {
                'email': 'mrsiro@gmail.com',
                'username': 'mrsiro@gmail.com',
                'password': 'Mrsiro12345@',
                'name': 'Mr.Siro',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'masew@gmail.com',
                'username': 'masew@gmail.com',
                'password': 'Masew12345@',
                'name': 'Masew',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'langld@gmail.com',
                'username': 'langld@gmail.com',
                'password': 'Langld12345@',
                'name': 'Lăng LD ',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path':None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'binz@gmail.com',
                'username': 'binz@gmail.com',
                'password': 'Binz12345@',
                'name': 'Binz',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'den@gmail.com',
                'username': 'den@gmail.com',
                'password': 'DDen12345@',
                'name': 'Đen',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'justatee@gmail.com',
                'username': 'justatee@gmail.com',
                'password': 'Justatee12345@',
                'name': 'JustaTee',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path':None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'wrenevans@gmail.com',
                'username': 'wrenevans@gmail.com',
                'password': 'Wrenevans12345@',
                'name': 'Wren Evans',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'mewamazing@gmail.com',
                'username': 'mewamazing@gmail.com',
                'password': 'Mewamazing12345@',
                'name': 'Mew Amazing',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'thanhbui@gmail.com',
                'username': 'thanhbui@gmail.com',
                'password': 'Thanhbui12345@',
                'name': 'Thanh Bùi',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'thanhlam@gmail.com',
                'username': 'thanhlam@gmail.com',
                'password': 'Thanhlam12345@',
                'name': 'Thanh Lam',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'tungduong@gmail.com',
                'username': 'tungduong@gmail.com',
                'password': 'Tungduong12345@',
                'name': 'Tùng Dương',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'lowg@gmail.com',
                'username': 'lowg@gmail.com',
                'password': 'Lowg12345@',
                'name': 'Low G',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': '2pillz@gmail.com',
                'username': '2pillz@gmail.com',
                'password': '2pillz12345@',
                'name': '2pillz',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'trungtran@gmail.com',
                'username': 'trungtran@gmail.com',
                'password': 'Trungtran12345@',
                'name': 'Trung Trần',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'wokeup@gmail.com',
                'username': 'wokeup@gmail.com',
                'password': 'Wokeup12345@',
                'name': 'WOKEUP ',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'greyd@gmail.com',
                'username': 'greyd@gmail.com',
                'password': 'Greyd12345@',
                'name': 'GREYD',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'masonnguyen@gmail.com',
                'username': 'masonnguyen@gmail.com',
                'password': 'Masonnguyen12345@',
                'name': 'Mason Nguyen',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'sterry@gmail.com',
                'username': 'sterry@gmail.com',
                'password': 'Sterry12345@',
                'name': 'Sterry',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'kingofrap@gmail.com',
                'username': 'kingofrap@gmail.com',
                'password': 'Kingofrap12345@',
                'name': 'King Of Rap ',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'machiot@gmail.com',
                'username': 'machiot@gmail.com',
                'password': 'Machiot12345@',
                'name': 'Machiot',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
            {
                'email': 'vstra@gmail.com',
                'username': 'vstra@gmail.com',
                'password': 'Vstra12345@',
                'name': 'VSTRA',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
             {
                'email': 'youngpuppy@gmail.com',
                'username': 'youngpuppy@gmail.com',
                'password': 'Youngpuppy12345@',
                'name': 'Young Puppy',
                'role': artist_role,  
                'is_active': True,
                'is_ban': False,
                'image_path': None,
                'created_at': timezone.make_aware(datetime.datetime(2025, 4, 13, 21, 3, 29)),
            },
        ]

        # Tạo người dùng
        for user_data in users_data:
            try:
                if not User.objects.filter(email=user_data['email']).exists():
                    user = User.objects.create_user(
                        email=user_data['email'],
                        username=user_data['username'],
                        password=user_data['password'],
                        role=user_data['role'],
                        name=user_data['name'],
                        is_active=user_data['is_active'],
                        is_ban=user_data['is_ban'],
                        image_path=user_data['image_path'],
                    )
                    # Cập nhật created_at
                    User.objects.filter(id=user.id).update(created_at=user_data['created_at'])
                    self.stdout.write(self.style.SUCCESS(f"Successfully created user: {user_data['email']}"))
                else:
                    self.stdout.write(self.style.WARNING(f"User {user_data['email']} already exists"))
            except Exception as e:
                self.stdout.write(self.style.ERROR(f"Error creating user {user_data['email']}: {str(e)}"))

        self.stdout.write(self.style.SUCCESS('Database seeding completed!'))